In [56]:
ndarray1 = np.array([1,2,3])
print(type(ndarray1), ndarray1)

print(ndarray1.shape)
print(ndarray1.ndim)

<class 'numpy.ndarray'> [1 2 3]
(3,)
1


In [64]:
ndarray1 = np.array([1, 2, 3])
print(type(ndarray1))
print(ndarray1.dtype)

ndarray1_int8 = ndarray1.astype(np.int8)
print(type(ndarray1_int8))
print(ndarray1_int8.dtype)

<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
int8


In [66]:
#  4, 5, 6을 ndarray에 담는다.
# dtype을 확인한 뒤 float16으로 변경하고 확인한다.

ndarray = np.array([4,5,6])
print(type(ndarray))
print(ndarray.dtype)

ndarray_float16 = ndarray.astype(np.float16)
print(type(ndarray_float16))
print(ndarray_float16.dtype)

<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
float16


In [71]:
# 1 ~ 10까지의 요소를 ndarray에 담는다.
# 각 요소에 5씩 더한다.

ndarray = np.array(list(range(1,11)))
ndarray + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [76]:
import numpy as np

# 0 ~ 9까지 1차원 ndarray
ndarray1 = np.arange(0,10, dtype=np.float16)
print(ndarray1.shape)
print(ndarray1)

# 2행 3열 요소 모두 0으로 초기화
ndarray2 = np.zeros((2,3))
print(ndarray2.shape)
print(ndarray2)

# 1차원 3칸 배열 요소 모두 1로 초기화
ndarray1 = np.ones((3,), dtype=np.int8)
print(ndarray1.shape)
print(ndarray1)

(10,)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
(3,)
[1 1 1]


In [81]:
ndarray1 = np.arange(8)
ndarray2 = ndarray1.reshape((2, 4))
print(ndarray2.shape)

# ndarray1의 차원을 2차원 2열로 변경
ndarray2 = ndarray1.reshape((-1,2))

# ndarray1을 2차원 1열로 변환
ndarray1.reshape((-1,1))

(2, 4)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [93]:
import numpy as np

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
ndarray1 = np.zeros((10, ), dtype = np.int32)
print(ndarray1, ndarray1.shape)

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray2 = np.ones((3,4))
print(ndarray2, ndarray2.shape)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(5)
print(ndarray1, ndarray1.shape)

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)
# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1,2))
print(ndarray2, ndarray2.shape)

# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8,-1))
print(ndarray2, ndarray2.shape)

# 3 Dimension으로 변경
ndarray3 = ndarray1.reshape((2,2,4))
print(ndarray3, ndarray3.shape)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1,1))
print(ndarray2, ndarray2.shape)

# ndarray3을 1 Dimension으로 변환
ndarray3 = ndarray3.reshape((-1,))
print(ndarray3, ndarray3.shape)

# ndarray1 = ndarray3.reshape((-1, ))


[0 0 0 0 0 0 0 0 0 0] (10,)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[0 1 2 3 4] (5,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] (8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] (8, 2)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]] (16, 1)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] (16,)
